use std::ffi::OsString;
use std::path::PathBuf;

use clap::{Args, Parser, Subcommand};

#[derive(Debug, Parser)]
#[command(
    name = "runsift",
    version,
    arg_required_else_help = true,
    about = "Capture a program or test run into a traceable diagnostic evidence bundle",
    long_about = "RunSift executes a program or test command, streams its output, collects selected logs and C++ diagnostics, then writes a compact local evidence bundle for developers, CI tools, and AI analysis.\n\nIt does not call an AI model or modify source code. Its job is to preserve what happened at runtime in a structured, redacted, and traceable form.",
    after_help = "QUICK START:\n  runsift run -- ./build/unit_tests\n  runsift run --log build/logs/app.log -- ctest --test-dir build --output-on-failure\n\nOUTPUT:\n  Each run creates .runsift/runs/<run_id>/ with summary.md, manifest.json,\n  events.jsonl, patterns.json, and any C++-specific evidence.\n\nRun `runsift help run` for collection options and more examples."
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    #[command(
        about = "Execute a program or test and collect its diagnostic evidence",
        long_about = "Execute exactly one program or test command while capturing stdout, stderr, selected log files, test reports, sanitizer findings, and crash metadata.\n\nRunSift writes an isolated evidence bundle after the command exits and returns the command's original exit code, so failures remain visible in local scripts and CI.",
        after_help = "EXAMPLES:\n  Run a test binary:\n    runsift run -- ./build/unit_tests\n\n  Capture spdlog output from CTest:\n    runsift run --log build/logs/app.log -- \\\n      ctest --test-dir build --output-on-failure\n\n  Capture structured CTest results:\n    runsift run --test-report build/ctest.xml -- \\\n      ctest --test-dir build --output-junit build/ctest.xml\n\nThe `--` separator is required. Everything after it is the program and its arguments."
    )]
    Run(RunArgs),
}

#[derive(Debug, Args)]
#[command(arg_required_else_help = true)]
pub struct RunArgs {
    /// Log file to snapshot before the command and collect after it exits.
    #[arg(long = "log", value_name = "PATH", help_heading = "EVIDENCE INPUTS")]
    pub logs: Vec<PathBuf>,

    /// JSON profile describing a project-specific spdlog line format.
    #[arg(
        long = "log-profile",
        value_name = "PATH",
        help_heading = "EVIDENCE INPUTS"
    )]
    pub log_profile: Option<PathBuf>,

    /// CTest or GoogleTest JUnit XML report generated by the wrapped command.
    #[arg(
        long = "test-report",
        value_name = "PATH",
        help_heading = "EVIDENCE INPUTS"
    )]
    pub test_reports: Vec<PathBuf>,

    /// Core dump to describe in the evidence bundle.
    #[arg(long = "core", value_name = "PATH", help_heading = "EVIDENCE INPUTS")]
    pub core_dumps: Vec<PathBuf>,

    /// Text report previously generated by GDB or LLDB.
    #[arg(
        long = "debugger-report",
        value_name = "PATH",
        help_heading = "EVIDENCE INPUTS"
    )]
    pub debugger_reports: Vec<PathBuf>,

    /// Stable run ID supplied by a caller or CI system.
    #[arg(long, value_name = "ID", help_heading = "CORRELATION")]
    pub run_id: Option<String>,

    /// Correlate this run with a larger batch.
    #[arg(long, value_name = "ID", help_heading = "CORRELATION")]
    pub batch_id: Option<String>,

    /// Correlate all unscoped evidence with a test case.
    #[arg(long, value_name = "ID", help_heading = "CORRELATION")]
    pub test_id: Option<String>,

    /// Parent directory for generated run bundles.
    #[arg(short, long, default_value = ".runsift/runs", help_heading = "OUTPUT")]
    pub output: PathBuf,

    /// Keep obvious secrets in the generated bundle.
    #[arg(long, default_value_t = false, help_heading = "OUTPUT")]
    pub no_redact: bool,

    /// Program and arguments to execute. Must follow the `--` separator.
    #[arg(
        required = true,
        last = true,
        allow_hyphen_values = true,
        value_name = "COMMAND"
    )]
    pub command: Vec<OsString>,
}
