use std::ffi::OsString;
use std::path::PathBuf;

use clap::{Args, Parser, Subcommand};

#[derive(Debug, Parser)]
#[command(version, about)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Run a command and package its failure evidence.
    Run(RunArgs),
}

#[derive(Debug, Args)]
pub struct RunArgs {
    /// Log file to snapshot before the command and collect after it exits.
    #[arg(long = "log", value_name = "PATH")]
    pub logs: Vec<PathBuf>,

    /// JSON profile describing a project-specific spdlog line format.
    #[arg(long = "log-profile", value_name = "PATH")]
    pub log_profile: Option<PathBuf>,

    /// CTest or GoogleTest JUnit XML report generated by the wrapped command.
    #[arg(long = "test-report", value_name = "PATH")]
    pub test_reports: Vec<PathBuf>,

    /// Core dump to describe in the evidence bundle.
    #[arg(long = "core", value_name = "PATH")]
    pub core_dumps: Vec<PathBuf>,

    /// Text report previously generated by GDB or LLDB.
    #[arg(long = "debugger-report", value_name = "PATH")]
    pub debugger_reports: Vec<PathBuf>,

    /// Stable run ID supplied by a caller or CI system.
    #[arg(long, value_name = "ID")]
    pub run_id: Option<String>,

    /// Correlate this run with a larger batch.
    #[arg(long, value_name = "ID")]
    pub batch_id: Option<String>,

    /// Correlate all unscoped evidence with a test case.
    #[arg(long, value_name = "ID")]
    pub test_id: Option<String>,

    /// Parent directory for generated run bundles.
    #[arg(short, long, default_value = ".runsift/runs")]
    pub output: PathBuf,

    /// Keep obvious secrets in the generated bundle.
    #[arg(long, default_value_t = false)]
    pub no_redact: bool,

    /// Command and arguments to execute. Place these after `--`.
    #[arg(required = true, trailing_var_arg = true, allow_hyphen_values = true)]
    pub command: Vec<OsString>,
}
