use std::ffi::OsString;
use std::path::PathBuf;

use clap::{Args, Parser, Subcommand, ValueEnum};

#[derive(Debug, Parser)]
#[command(
    name = "runsift",
    version,
    arg_required_else_help = true,
    about = "Turn runtime evidence into traceable diagnostic context for developers and AI",
    long_about = "RunSift captures a program or test run into a compact local evidence bundle, then selects high-signal evidence for developers, CI tools, and AI analysis.\n\n`run` and `context` stay local. Only the explicit `analyze` command invokes the model adapter you select. RunSift validates that model findings cite evidence from the generated context and never modifies source code.",
    after_help = "QUICK START:\n  runsift run -- ./build/unit_tests\n  runsift context .runsift/runs/<run_id> --token-budget 8000\n\nOUTPUT:\n  `run` creates .runsift/runs/<run_id>/ with summary.md and structured evidence.\n  `context` writes ai/context.json and ai/prompt.md without calling a model.\n  `analyze` explicitly sends that context to a configured model adapter.\n\nRun `runsift help <COMMAND>` for options and examples."
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    #[command(
        about = "Execute a program or test and collect its diagnostic evidence",
        long_about = "Execute exactly one program or test command while capturing stdout, stderr, selected log files, test reports, sanitizer findings, and crash metadata.\n\nRunSift writes an isolated evidence bundle after the command exits and returns the command's original exit code, so failures remain visible in local scripts and CI.",
        after_help = "EXAMPLES:\n  Run a test binary:\n    runsift run -- ./build/unit_tests\n\n  Capture spdlog output from CTest:\n    runsift run --log build/logs/app.log -- \\\n      ctest --test-dir build --output-on-failure\n\n  Capture structured CTest results:\n    runsift run --test-report build/ctest.xml -- \\\n      ctest --test-dir build --output-junit build/ctest.xml\n\nThe `--` separator is required. Everything after it is the program and its arguments."
    )]
    Run(RunArgs),

    #[command(
        about = "Build a token-budgeted, citation-ready AI context from a bundle",
        long_about = "Read an existing RunSift evidence bundle, select the highest-signal evidence under an approximate token budget, and generate a stable diagnostic context plus a model prompt.\n\nThis command is local-only. It does not call a model or upload evidence.",
        after_help = "EXAMPLES:\n  Write ai/context.json and ai/prompt.md:\n    runsift context .runsift/runs/run_20260802_1234\n\n  Print machine-readable context for another tool:\n    runsift context .runsift/runs/run_20260802_1234 --stdout\n\nToken counts are deterministic estimates, not provider-specific tokenizer results."
    )]
    Context(ContextArgs),

    #[command(
        about = "Analyze a bundle through an explicit local or OpenAI-compatible adapter",
        long_about = "Build the same citation-ready context as `runsift context`, invoke the selected model adapter, validate the returned JSON, and reject findings or hypotheses that do not cite evidence included in the context.\n\nNo model is contacted unless this command is explicitly run.",
        after_help = "EXAMPLES:\n  Local command adapter (prompt is sent on stdin):\n    runsift analyze .runsift/runs/<run_id> local -- ollama run qwen3\n\n  OpenAI Responses-compatible endpoint:\n    runsift analyze .runsift/runs/<run_id> openai \\\n      --base-url https://api.openai.com/v1 \\\n      --model <MODEL> --api-key-env OPENAI_API_KEY"
    )]
    Analyze(AnalyzeArgs),
}

#[derive(Debug, Args)]
#[command(arg_required_else_help = true)]
pub struct RunArgs {
    /// Log file to snapshot before the command and collect after it exits.
    #[arg(long = "log", value_name = "PATH", help_heading = "EVIDENCE INPUTS")]
    pub logs: Vec<PathBuf>,

    /// JSON profile describing a project-specific spdlog line format.
    #[arg(
        long = "log-profile",
        value_name = "PATH",
        help_heading = "EVIDENCE INPUTS"
    )]
    pub log_profile: Option<PathBuf>,

    /// CTest or GoogleTest JUnit XML report generated by the wrapped command.
    #[arg(
        long = "test-report",
        value_name = "PATH",
        help_heading = "EVIDENCE INPUTS"
    )]
    pub test_reports: Vec<PathBuf>,

    /// Core dump to describe in the evidence bundle.
    #[arg(long = "core", value_name = "PATH", help_heading = "EVIDENCE INPUTS")]
    pub core_dumps: Vec<PathBuf>,

    /// Text report previously generated by GDB or LLDB.
    #[arg(
        long = "debugger-report",
        value_name = "PATH",
        help_heading = "EVIDENCE INPUTS"
    )]
    pub debugger_reports: Vec<PathBuf>,

    /// Stable run ID supplied by a caller or CI system.
    #[arg(long, value_name = "ID", help_heading = "CORRELATION")]
    pub run_id: Option<String>,

    /// Correlate this run with a larger batch.
    #[arg(long, value_name = "ID", help_heading = "CORRELATION")]
    pub batch_id: Option<String>,

    /// Correlate all unscoped evidence with a test case.
    #[arg(long, value_name = "ID", help_heading = "CORRELATION")]
    pub test_id: Option<String>,

    /// Parent directory for generated run bundles.
    #[arg(short, long, default_value = ".runsift/runs", help_heading = "OUTPUT")]
    pub output: PathBuf,

    /// Keep obvious secrets in the generated bundle.
    #[arg(long, default_value_t = false, help_heading = "OUTPUT")]
    pub no_redact: bool,

    /// Program and arguments to execute. Must follow the `--` separator.
    #[arg(
        required = true,
        last = true,
        allow_hyphen_values = true,
        value_name = "COMMAND"
    )]
    pub command: Vec<OsString>,
}

#[derive(Debug, Args)]
pub struct ContextArgs {
    /// Existing RunSift evidence bundle directory.
    #[arg(value_name = "BUNDLE")]
    pub bundle: PathBuf,

    /// Approximate maximum tokens for the generated model prompt.
    #[arg(long, default_value_t = 8_000, value_name = "TOKENS")]
    pub token_budget: usize,

    /// Context JSON path. Defaults to BUNDLE/ai/context.json.
    #[arg(long, value_name = "PATH", conflicts_with = "stdout")]
    pub output: Option<PathBuf>,

    /// Model prompt path. Defaults to BUNDLE/ai/prompt.md.
    #[arg(long, value_name = "PATH", conflicts_with = "stdout")]
    pub prompt_output: Option<PathBuf>,

    /// Print context JSON to stdout instead of writing files.
    #[arg(long)]
    pub stdout: bool,

    /// Replace existing generated context files.
    #[arg(long)]
    pub force: bool,
}

#[derive(Debug, Args)]
pub struct AnalyzeArgs {
    /// Existing RunSift evidence bundle directory.
    #[arg(value_name = "BUNDLE")]
    pub bundle: PathBuf,

    /// Approximate maximum tokens for model input.
    #[arg(long, default_value_t = 8_000, value_name = "TOKENS")]
    pub token_budget: usize,

    /// Validated analysis JSON path. Defaults to BUNDLE/ai/analysis.json.
    #[arg(long, value_name = "PATH")]
    pub output: Option<PathBuf>,

    /// Replace an existing analysis file.
    #[arg(long)]
    pub force: bool,

    #[command(subcommand)]
    pub adapter: AnalyzeAdapter,
}

#[derive(Debug, Subcommand)]
pub enum AnalyzeAdapter {
    /// Send the prompt to a local process over stdin and read JSON from stdout.
    Local(LocalAdapterArgs),

    /// Call an OpenAI-compatible Responses or Chat Completions endpoint.
    Openai(OpenAiAdapterArgs),
}

#[derive(Debug, Args)]
pub struct LocalAdapterArgs {
    /// Local model command. Must follow the `--` separator.
    #[arg(
        required = true,
        last = true,
        allow_hyphen_values = true,
        value_name = "COMMAND"
    )]
    pub command: Vec<OsString>,
}

#[derive(Debug, Args)]
pub struct OpenAiAdapterArgs {
    /// API base URL containing the /responses endpoint.
    #[arg(long, default_value = "https://api.openai.com/v1", value_name = "URL")]
    pub base_url: String,

    /// Model identifier accepted by the endpoint.
    #[arg(long, value_name = "MODEL")]
    pub model: String,

    /// Environment variable containing a bearer token. Omit for unauthenticated local servers.
    #[arg(long, value_name = "NAME")]
    pub api_key_env: Option<String>,

    /// HTTP timeout in seconds.
    #[arg(long, default_value_t = 120, value_name = "SECONDS")]
    pub timeout: u64,

    /// Ask for JSON in the prompt without sending a strict response schema.
    #[arg(long)]
    pub plain_json: bool,

    /// OpenAI-compatible endpoint style.
    #[arg(long, value_enum, default_value_t = OpenAiApi::Responses)]
    pub api: OpenAiApi,
}

#[derive(Debug, Clone, Copy, ValueEnum)]
pub enum OpenAiApi {
    /// POST /responses using the current OpenAI Responses shape.
    Responses,
    /// POST /chat/completions for compatible servers using the older chat shape.
    ChatCompletions,
}
